# -*- coding: utf-8 -*-

################################################################################
# Form generated from reading UI file 'Casio_template.ui'
##
# Created by: Qt User Interface Compiler version 6.1.2
##
# WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################
from PySide2 import QtWidgets, QtCore, QtGui
from PySide2.QtCore import Qt

import ressource_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 990)
        MainWindow.setMaximumSize(QtCore.QSize(660, 1000))
        MainWindow.setStyleSheet("background-image: url(:/image/casioBg.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-10, -50, 661, 1061))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.widget.setFont(font)
        self.widget.setStyleSheet("background-image: url(:/background/image/casioBg.png);\n"
                                  "background-image: url(:/background/image/casioBg.png);")
        self.widget.setObjectName("widget")
        self.b8 = QtWidgets.QPushButton(self.widget)
        self.b8.setGeometry(QtCore.QRect(220, 691, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.b8.setFont(font)
        self.b8.setAutoFillBackground(False)
        self.b8.setStyleSheet("color: white;\n"
                              "background-color: rgb(17, 17, 20);\n"
                              "border-radius: 5px;")
        self.b8.setFlat(False)
        self.b8.setObjectName("b8")
        self.b9 = QtWidgets.QPushButton(self.widget)
        self.b9.setGeometry(QtCore.QRect(306, 691, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.b9.setFont(font)
        self.b9.setAutoFillBackground(False)
        self.b9.setStyleSheet("color: white;\n"
                              "background-color: rgb(17, 17, 20);\n"
                              "border-radius: 5px;")
        self.b9.setFlat(False)
        self.b9.setObjectName("b9")
        self.b6 = QtWidgets.QPushButton(self.widget)
        self.b6.setGeometry(QtCore.QRect(306, 759, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.b6.setFont(font)
        self.b6.setAutoFillBackground(False)
        self.b6.setStyleSheet("color: white;\n"
                              "background-color: rgb(17, 17, 20);\n"
                              "border-radius: 5px;")
        self.b6.setFlat(False)
        self.b6.setObjectName("b6")
        self.b5 = QtWidgets.QPushButton(self.widget)
        self.b5.setGeometry(QtCore.QRect(220, 759, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.b5.setFont(font)
        self.b5.setAutoFillBackground(False)
        self.b5.setStyleSheet("color: white;\n"
                              "background-color: rgb(17, 17, 20);\n"
                              "border-radius: 5px;")
        self.b5.setFlat(False)
        self.b5.setObjectName("b5")
        self.b4 = QtWidgets.QPushButton(self.widget)
        self.b4.setGeometry(QtCore.QRect(130, 759, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.b4.setFont(font)
        self.b4.setAutoFillBackground(False)
        self.b4.setStyleSheet("color: white;\n"
                              "background-color: rgb(17, 17, 20);\n"
                              "border-radius: 5px;")
        self.b4.setFlat(False)
        self.b4.setObjectName("b4")
        self.b2 = QtWidgets.QPushButton(self.widget)
        self.b2.setGeometry(QtCore.QRect(220, 828, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setAutoFillBackground(False)
        self.b2.setStyleSheet("color: white;\n"
                              "background-color: rgb(17, 17, 20);\n"
                              "border-radius: 5px;")
        self.b2.setFlat(False)
        self.b2.setObjectName("b2")
        self.b3 = QtWidgets.QPushButton(self.widget)
        self.b3.setGeometry(QtCore.QRect(306, 828, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.b3.setFont(font)
        self.b3.setAutoFillBackground(False)
        self.b3.setStyleSheet("color: white;\n"
                              "background-color: rgb(17, 17, 20);\n"
                              "border-radius: 5px;")
        self.b3.setFlat(False)
        self.b3.setObjectName("b3")
        self.b0 = QtWidgets.QPushButton(self.widget)
        self.b0.setGeometry(QtCore.QRect(130, 891, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.b0.setFont(font)
        self.b0.setAutoFillBackground(False)
        self.b0.setStyleSheet("color: white;\n"
                              "background-color: rgb(17, 17, 20);\n"
                              "border-radius: 5px;")
        self.b0.setFlat(False)
        self.b0.setObjectName("b0")
        self.dot = QtWidgets.QPushButton(self.widget)
        self.dot.setGeometry(QtCore.QRect(220, 891, 71, 51))
        font = QtGui.QFont()
        font.setFamily("French Script MT")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.dot.setFont(font)
        self.dot.setAutoFillBackground(False)
        self.dot.setStyleSheet("color: white;\n"
                               "background-color: rgb(17, 17, 20);\n"
                               "border-radius: 5px;")
        self.dot.setFlat(False)
        self.dot.setObjectName("dot")
        self.exp = QtWidgets.QPushButton(self.widget)
        self.exp.setGeometry(QtCore.QRect(306, 891, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.exp.setFont(font)
        self.exp.setAutoFillBackground(False)
        self.exp.setStyleSheet("color: white;\n"
                               "background-color: rgb(17, 17, 20);\n"
                               "border-radius: 5px;")
        self.exp.setFlat(False)
        self.exp.setObjectName("exp")
        self.bc = QtWidgets.QPushButton(self.widget)
        self.bc.setGeometry(QtCore.QRect(392, 691, 70, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.bc.setFont(font)
        self.bc.setStyleSheet("border-radius: 5px;\n"
                              "background-color: rgb(149, 69, 57);\n"
                              "color: #FFF;")
        self.bc.setObjectName("bc")
        self.bac = QtWidgets.QPushButton(self.widget)
        self.bac.setGeometry(QtCore.QRect(481, 691, 70, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.bac.setFont(font)
        self.bac.setStyleSheet("border-radius: 5px;\n"
                               "background-color: rgb(149, 69, 57);\n"
                               "color: #FFF;")
        self.bac.setObjectName("bac")
        self.noun = QtWidgets.QPushButton(self.widget)
        self.noun.setGeometry(QtCore.QRect(390, 760, 71, 50))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.noun.setFont(font)
        self.noun.setAutoFillBackground(False)
        self.noun.setStyleSheet("color: white;\n"
                                "background-color: rgb(17, 17, 20);\n"
                                "border-radius: 5px;")
        self.noun.setFlat(False)
        self.noun.setObjectName("noun")
        self.more = QtWidgets.QPushButton(self.widget)
        self.more.setGeometry(QtCore.QRect(390, 828, 72, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.more.setFont(font)
        self.more.setAutoFillBackground(False)
        self.more.setStyleSheet("color: white;\n"
                                "background-color: rgb(17, 17, 20);\n"
                                "border-radius: 5px;")
        self.more.setFlat(False)
        self.more.setObjectName("more")
        self.less = QtWidgets.QPushButton(self.widget)
        self.less.setGeometry(QtCore.QRect(481, 828, 70, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.less.setFont(font)
        self.less.setAutoFillBackground(False)
        self.less.setStyleSheet("color: white;\n"
                                "background-color: rgb(17, 17, 20);\n"
                                "border-radius: 5px;")
        self.less.setFlat(False)
        self.less.setObjectName("less")
        self.divide = QtWidgets.QPushButton(self.widget)
        self.divide.setGeometry(QtCore.QRect(481, 760, 70, 50))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.divide.setFont(font)
        self.divide.setAutoFillBackground(False)
        self.divide.setStyleSheet("color: white;\n"
                                  "background-color: rgb(17, 17, 20);\n"
                                  "border-radius: 5px;")
        self.divide.setFlat(False)
        self.divide.setObjectName("divide")
        self.b1 = QtWidgets.QPushButton(self.widget)
        self.b1.setGeometry(QtCore.QRect(130, 828, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setAutoFillBackground(False)
        self.b1.setStyleSheet("color: white;\n"
                              "background-color: rgb(17, 17, 20);\n"
                              "border-radius: 5px;")
        self.b1.setFlat(False)
        self.b1.setObjectName("b1")
        self.b7 = QtWidgets.QPushButton(self.widget)
        self.b7.setEnabled(True)
        self.b7.setGeometry(QtCore.QRect(130, 691, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.b7.setFont(font)
        self.b7.setMouseTracking(False)
        self.b7.setAutoFillBackground(False)
        self.b7.setStyleSheet("color: white;\n"
                              "background-color: rgb(0, 0, 0);\n"
                              "border-radius: 5px;\n"
                              "\n"
                              "hover:{\n"
                              "background-color: grey:\n"
                              "}")
        self.b7.setCheckable(False)
        self.b7.setFlat(False)
        self.b7.setObjectName("b7")
        self.equal = QtWidgets.QPushButton(self.widget)
        self.equal.setGeometry(QtCore.QRect(390, 890, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.equal.setFont(font)
        self.equal.setAutoFillBackground(False)
        self.equal.setStyleSheet("color: white;\n"
                                 "background-color: rgb(17, 17, 20);\n"
                                 "border-radius: 5px;")
        self.equal.setFlat(False)
        self.equal.setObjectName("equal")
        self.Mmore = QtWidgets.QPushButton(self.widget)
        self.Mmore.setGeometry(QtCore.QRect(481, 890, 70, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Mmore.setFont(font)
        self.Mmore.setAutoFillBackground(False)
        self.Mmore.setStyleSheet("color: white;\n"
                                 "background-color: rgb(17, 17, 20);\n"
                                 "border-radius: 5px;")
        self.Mmore.setFlat(False)
        self.Mmore.setObjectName("Mmore")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(160, 310, 361, 101))
        self.lineEdit.setAlignment(Qt.AlignRight)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-image: url(:/background/image/screenColor.png);\n"
                                    "font-familly: \"arial\";\n"
                                    "border-radius: 5px;")
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClosed = QtWidgets.QAction(MainWindow)
        self.actionClosed.setObjectName("actionClosed")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setEnabled(True)
        self.actionNew.setObjectName("actionNew")
        self.menuFile.addAction(self.actionClosed)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setWhatsThis(_translate(
            "MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.b8.setText(_translate("MainWindow", "8"))
        self.b9.setText(_translate("MainWindow", "9"))
        self.b6.setText(_translate("MainWindow", "6"))
        self.b5.setText(_translate("MainWindow", "5"))
        self.b4.setText(_translate("MainWindow", "4"))
        self.b2.setText(_translate("MainWindow", "2"))
        self.b3.setText(_translate("MainWindow", "3"))
        self.b0.setText(_translate("MainWindow", "0"))
        self.dot.setText(_translate("MainWindow", "."))
        self.exp.setText(_translate("MainWindow", "EXP"))
        self.bc.setText(_translate("MainWindow", "C"))
        self.bac.setText(_translate("MainWindow", "AC"))
        self.noun.setText(_translate("MainWindow", "X"))
        self.more.setText(_translate("MainWindow", "+"))
        self.less.setText(_translate("MainWindow", "-"))
        self.divide.setText(_translate("MainWindow", "/"))
        self.b1.setText(_translate("MainWindow", "1"))
        self.b7.setText(_translate("MainWindow", "7"))
        self.equal.setText(_translate("MainWindow", "="))
        self.Mmore.setText(_translate("MainWindow", "M+"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionClosed.setText(_translate("MainWindow", "Closed"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionNew.setText(_translate("MainWindow", "New"))
    # retranslateUi
